"""Public contract for RecallLedger's tenant-scoped event stream."""

from .events import (
    CommandId,
    ContractViolation,
    EventKind,
    LedgerEvent,
    NoteContent,
    NoteId,
    TenantId,
    TombstoneReason,
    decode_event,
    new_command_id,
    new_note_id,
    new_tenant_id,
)
from .retrieval import (
    LexicalQuery,
    LexicalScore,
    LexicalTokenStreams,
    RetrievalContractError,
    compile_lexical_query,
    lexical_token_streams,
    score_lexical_content,
)
from .storage import (
    Fts5CandidateAudit,
    HistoryPage,
    LedgerStorageError,
    SearchCitation,
    SearchHit,
    SearchResults,
    SQLiteLedger,
    StorageStatus,
    TransitionResult,
)

__all__ = [
    "CommandId",
    "ContractViolation",
    "EventKind",
    "Fts5CandidateAudit",
    "HistoryPage",
    "LedgerEvent",
    "LedgerStorageError",
    "LexicalQuery",
    "LexicalScore",
    "LexicalTokenStreams",
    "NoteContent",
    "NoteId",
    "RetrievalContractError",
    "SQLiteLedger",
    "SearchCitation",
    "SearchHit",
    "SearchResults",
    "StorageStatus",
    "TenantId",
    "TombstoneReason",
    "TransitionResult",
    "compile_lexical_query",
    "decode_event",
    "lexical_token_streams",
    "new_command_id",
    "new_note_id",
    "new_tenant_id",
    "score_lexical_content",
]
